version: "3"
services:
  server:
    build:
      context: ./backend/EventScheduler
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080

  ui:
    build:
      context: ./frontend/event-scheduler-angular
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - 4200:80
    links:
      - server
